TERM_PROGRAM=vscode
TERM=xterm-256color
SHELL=/bin/zsh
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000b7tc002syl/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.OpF08lRwjU/Render
TERM_PROGRAM_VERSION=1.63.2
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
ZSH=/Users/asaffroy/.oh-my-zsh
USER=asaffroy
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.5nZJseO4Vr/Listeners
__CF_USER_TEXT_ENCODING=0x167D3:0x0:0x0
PAGER=less
LSCOLORS=Gxfxcxdxbxegedabagacad
PATH=/Users/asaffroy/.brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/opt/X11/bin:/Users/asaffroy/.brew/bin
_=/usr/bin/env
PWD=/Users/asaffroy/Documents/GitHub/42-minishell
LANG=en_US.UTF-8
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=2
HOME=/Users/asaffroy
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
LESS=-R
LOGNAME=asaffroy
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n000b7tc002syl/T/vscode-git-76e25a797a.sock
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/MacOS/Electron
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
DISPLAY=/private/tmp/com.apple.launchd.9MwxDZtajI/org.xquartz:0
SECURITYSESSIONID=186e8
COLORTERM=truecolor
